kramdown:
  footnote_backlink: "&#8617;&#65038;"

plugins:
  - jekyll-seo-tag

title: Shumaila Chini
tagline: Independent Product & Experience Designer
description: Portfolio and more of Shumaila Chini, independent product & experience designer.
Author: Shumaila Chini
image: "/img/og-img.png"
lang: en_GB
twitter:
  username: ampinsk
  card: summary
