kramdown:
  footnote_backlink: "&#8617;&#65038;"

plugins:
  - jekyll-seo-tag

title: Shumaila Chini
tagline: Product & Experience Designer
description: Portfolio and more of Shumaila Chini, product & experience designer.
Author: Shumaila Chini
image: "/img/og-logo.png"
lang: en_GB
twitter:
  username: chini_shumaila
  card: summary
